### ISSUE TITLE
auto-generated DELETE function works, but also prints an error to the terminal

### ISSUE THREAD

**Issue by msewell17** [haskell-servant/servant-client#1]
I am using servant and servant-client to query a postgresql db. My delete function removes the correct record, but also prints this error to the terminal: "HTTP DELETE request returned invalid json: not enough input". I have a GET function that does nearly the same thing, but returns an object instead of ( ) and it doesn't throw an error.

**Comment by alpmestan** [comment]
Hey,

Thanks for the report! Could you provide us with a minimal example that triggers this error? If not I can try reproducing it but it would obviously speed up the process.

Thank you!

**Comment by msewell17** [comment]
I'll be in the field tomorrow morning and early afternoon but I should be
able to do that when I get in the office later tomorrow

**Comment by msewell17** [comment]
I ended up fixing the problem by not using a Delete route at all, and
instead used another Get route that acted as a Delete route.

On Mon, Jan 5, 2015 at 7:43 PM, Alp Mestanogullari <notifications@github.com

**Comment by alpmestan** [comment]
I'm annoyed for you that you have to go through these hoops. Can you nonetheless send me the buggy code so that I make sure this never happens again?

**Comment by msewell17** [comment]
here is the bulk of my code, and it all works flawlessly as of now.

**Comment by alpmestan** [comment]
I don't see it...? It seems you answered by email but I'm not sure the code made it to the github issue if you've attached it to the email.

**Comment by msewell17** [comment]
Yeah I attached it and it isn't showing up. Want me to send it to a
different email?

On Thu, Jan 8, 2015 at 3:12 PM, Alp Mestanogullari <notifications@github.com

**Comment by alpmestan** [comment]
You can either paste it on the github issue: https://github.com/haskell-servant/servant-client/issues/1 or send the code my way to alpmestan@gmail.com -- thanks!

**Comment by christian-marie** [comment]
Fixed by #5, thanks @tvh.
