### ISSUE TITLE
Better error reporting

### ISSUE THREAD

**Issue by tvh** [haskell-servant/servant-client#12]
The current implementation works over `EitherT String IO a`. This gives some rudimentary error reporting, but makes it impossible to handle the errors in any way. I would like to actually know if it was just a status code other than 200,201,204,... or if there was an error parsing the response data. That said, maybe it should be something along the lines of `EitherT String IO (Response a)`

```.haskell
data Response a =
    Success a
    Failure Status MediaType ByteString
```

Maybe there is a way to make it more accessible, but I can't thik of anything ad-hoc. This could obviously be broken down to `EitherT String IO a` again for simpler usage is necessary.

**Comment by alpmestan** [comment]
Hmm... How about just `IO (Response a)`? I don't see what the `String` brings to the table if we enhance the return type with success/failure information.

**Comment by tvh** [comment]
Yes, I think that might be a better alternative.
```.haskell
data Response a =
    Success a
    FailureResponse Status MediaType ByteString
    DecodeFailure String MediaType ByteString
    UnsupportedContentType MediaType ByteString
```

**Comment by alpmestan** [comment]
Can we close this issue, given that #14 has been merged?
