### ISSUE TITLE
Access to full Response body

### ISSUE THREAD

**Issue by tvh** [haskell-servant/servant-client#16]
Sometimes it is necessary to inspect more about a response than just the body. Some services will return important information in the header. It would be nice to have a mechanism to do this.

One option would be to change the instance for `Raw`, such that it returns the Full response instead of just parts of it. This would also be in symmetry to the server, where you have full access to wai.

**Comment by jkarni** [comment]
:+1: on changing the instance for `Raw`. I guess we also need a `SetsHeader` combinator in `servant` - and then an instance for it in `servant-client`.

**Comment by alpmestan** [comment]
+1 for `Raw`. Much less so for `SetsHeader` unless we really have no better solution: `SetsXXX` stuffs hardly compose unfortunately.

**Comment by jkarni** [comment]
This issue was moved to haskell-servant/servant#34
