### ISSUE TITLE
DELETE doesn't allow for response body

### ISSUE THREAD

**Issue by Fuuzetsu** [haskell-servant/servant-client#19]
I have an API here that I DELETE to and which returns 200 (so we get `Left "HTTP DELETE request failed with status: 200 - OK"`, another issue) and some body which we can not process because unlike `Put` or `Post`, we can't parametrise the `Delete`.

**Comment by christian-marie** [comment]
I agree that any 2xx seems fine. I'm not so sure about parametrising Delete. I'm personally okay with parametrising everything with a body and having () mean no-content.

**Comment by Fuuzetsu** [comment]
Well, I have a DELETE I need to do and I have some body I need to read back, not much choice on the matter. I believe it's perfectly valid for a service to do this.

`()` for no body seems reasonable, it is certainly a step up from no body and forcing unit.

**Comment by christian-marie** [comment]
I can implement this, @alpmestan @alpmestan @soenkehahn -- Do we want to break everybody's DELETE?

**Comment by alpmestan** [comment]
This just comes from me reading that Delete *most of the time* return an empty body but I don't mind adding one of course! We will already break everybody's DELETE with this release I think?

**Comment by christian-marie** [comment]
To clarify: ```data Delete a :: * -> *```

**Comment by jkarni** [comment]
:+1:

**Comment by jkarni** [comment]
This issue was moved to haskell-servant/servant#33
