### ISSUE TITLE
Many return codes are not accounted for

### ISSUE THREAD

**Issue by Fuuzetsu** [haskell-servant/servant-client#20]
In the wild, methods may return one of many codes but servant-client only expects a very narrow range.

It should be extended to encompass at least the codes at http://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html

I mentioned this on IRC some days ago but didn't see an issue on it.

**Comment by alpmestan** [comment]
Oh, wonderful, back when we published 0.2 I didn't manage to find such a document. I'd definitely accept patches that take this into account if you feel like cooking one up :)
