### ISSUE TITLE
Fix `BaseUrl`

### ISSUE THREAD

**Issue by jkarni** [haskell-servant/servant-client#24]
`BaseUrl` should either be just be an argument to `client`, or the *first* argument to every function. (The former is, I think, preferable).

**Comment by thsutton** [comment]
I agree 100%

@tvh would up writing a small client module for each of our APIs to export a version of the client fns with this change.

**Comment by soenkehahn** [comment]
I also agree very much. IIRC I tried to do the latter once (making it the *first* argument of every function) and failed to make it type-check.

**Comment by alpmestan** [comment]
I'd definitely go with the first proposition. If anyone feels like putting that patch together, please go ahead, otherwise I'll take care of it next week.

**Comment by jkarni** [comment]
This issue was moved to haskell-servant/servant#32
